### ISSUE TITLE
project name & README

### ISSUE THREAD

**Issue by aquynh** [arbor-jjones/volatility_plugins#2]
i think the project can have a better name, as "volatility_plugins" is not clear.

besides, README is currently more or less empty now, without any information on what this project is doing.

cheers.

**Comment by jjo-sec** [comment]
Updated the readme with more information. 

This is a personal collection of plugins for the volatility framework so the name fits.

**Comment by aquynh** [comment]
ok got it, thanks for clarifying.

**Comment by aquynh** [comment]
we linked to your project from our website just now: http://capstone-engine.org/showcase.html

btw, there are quite a few of plugins officially available in Volatility using Distorm at the moment. would love to see those converted to use Capstone in the future :-)

thanks.
